services:
  db:
    image: postgres:alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bun_api
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
